version: '3'

services:
    database:
        image: registry.meter4.me:25410/cloud-database
        environment:
            POSTGRES_USER: "m4m"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "m4m"
        restart: always
    backend:
        image: registry.meter4.me:25410/cloud-backend
        depends_on:
            - database
        restart: always
    frontend:
        image: registry.meter4.me:25410/cloud-frontend
        ports:
            - 80:80
            - 443:443
        depends_on:
            - backend
            - frontend-admin
        restart: always
        volumes:
            - /etc/ssl/meter4.me/cert.pem:/etc/ssl/cert.pem
            - /etc/ssl/meter4.me/privkey.pem:/etc/ssl/privkey.pem
    frontend-admin:
        image: registry.meter4.me:25410/cloud-frontend-admin
        restart: always
    sync:
        image: registry.meter4.me:25410/cloud-sync
        restart: always
        depends_on:
            - database
